#!/bin/bash
#SBATCH -J test_file                         # Job name
#SBATCH --mail-type=ALL                      # Request status by email 
#SBATCH --mail-user=ah2288@cornell.edu        # Email address to send results to.
#SBATCH -N 1                                 # Total number of nodes requested
#SBATCH -n 4                                 # Total number of cores requested
#SBATCH --get-user-env                       # retrieve the users login environment
#SBATCH --mem=128000                           # server memory requested (per node)
#SBATCH -t 96:00:00                           # Time limit (hh:mm:ss)
#SBATCH --partition=seo                       # Request partition
#SBATCH --gres=gpu:a6000:1                    # Type/number of GPUs needed
cd /home/ah2288/AV-3DGS && bash train.sh